# Generated by Django 4.1.4 on 2022-12-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Funded', 'Funded'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
